const ADD_FOOD = 'ADD_FOOD'
const GET_FOOD = 'GET_FOOD'
const REMOVE_FOOD = 'REMOVE_FOOD'
const MODE_APP = 'MODE_APP'
const LANGUAGE_APP = 'LANGUAGE_APP'
const ADD_CARD = 'ADD_CARD'
const REMOVE_CARD_ITEM = 'REMOVE_CARD_ITEM'
const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT'
const AUTH_START = 'AUTH_START'
const AUTH_SUCCESS = 'AUTH_SUCCESS'
const AUTH_FAILED = 'AUTH_FAILED'
const AUTH_LOGOUT = 'AUTH_LOGOUT'

export {
  ADD_FOOD,
  GET_FOOD,
  REMOVE_FOOD,
  MODE_APP,
  LANGUAGE_APP,
  ADD_CARD,
  REMOVE_CARD_ITEM,
  REGISTER_ACCOUNT,
  AUTH_START,
  AUTH_SUCCESS,
  AUTH_FAILED,
  AUTH_LOGOUT
}