const ADD_FOOD = 'ADD_FOOD'
const GET_FOOD = 'GET_FOOD'
const REMOVE_FOOD = 'REMOVE_FOOD'
const MODE_APP = 'MODE_APP'
const LANGUAGE_APP = 'LANGUAGE_APP'
const ADD_CARD = 'ADD_CARD'
const REMOVE_CARD_ITEM = 'REMOVE_CARD_ITEM'

export {
  ADD_FOOD,
  GET_FOOD,
  REMOVE_FOOD,
  MODE_APP,
  LANGUAGE_APP,
  ADD_CARD,
  REMOVE_CARD_ITEM
}