const ADD_FOOD = 'ADD_FOOD'
const REMOVE_FOOD = 'REMOVE_FOOD'
const SELECT_FOOD = 'SELECT_FOOD'
const MODE_APP = 'MODE_APP'
const LANGUAGE_APP = 'LANGUAGE_APP'

export {
  ADD_FOOD,
  REMOVE_FOOD,
  SELECT_FOOD,
  MODE_APP,
  LANGUAGE_APP
}